package com.shadowborne_games.oathsworn.book;

import com.shadowborne_games.oathsworn.R;

/* loaded from: classes.dex */
public final class Chapter21 extends Book {
    public Chapter21() {
        this.sections = new Section[39];
        this.clue = new int[]{-1};
        this.sections[0] = new Section(R.string.pop21_1_1__b, this.z, this.z, this.z, R.raw.chp21_1_1__a, this.z, this.z, this.z, R.string.chp21_1_1__a, this.z, this.z, this.z, new LocationsAdded(new int[]{-1}), new ShowLocations(false), new IsLocation(false), new ClearLocationsList(false), new RemoveSpecificLocations(new int[]{-1}), new TimeAdded(-1), new ImageLinks(new int[]{-1}), new ImagePositions(new int[]{-1}), new Choice(R.string.btn_continue, 1));
        this.sections[1] = new Section(R.string.pop21_1_2__b, this.z, this.z, this.z, R.raw.chp21_1_2__a, this.z, this.z, this.z, R.string.chp21_1_2__a, this.z, this.z, this.z, new LocationsAdded(new int[]{-1}), new ShowLocations(false), new IsLocation(false), new ClearLocationsList(false), new RemoveSpecificLocations(new int[]{-1}), new TimeAdded(-1), new ImageLinks(new int[]{-1}), new ImagePositions(new int[]{-1}), new Choice(R.string.btn_continue, 2));
        this.sections[2] = new Section(R.string.pop21_1_3__b, this.z, this.z, this.z, R.raw.chp21_1_3__a, this.z, this.z, this.z, R.string.chp21_1_3__a, this.z, this.z, this.z, new LocationsAdded(new int[]{-1}), new ShowLocations(false), new IsLocation(false), new ClearLocationsList(false), new RemoveSpecificLocations(new int[]{-1}), new TimeAdded(-1), new ImageLinks(new int[]{R.drawable.ch21_1_3__p1}), new ImagePositions(new int[]{1}), new Choice(R.string.btn_succeed, 3), new Choice(R.string.btn_fail, 4));
        this.sections[3] = new Section(R.string.pop21_1_4__b, this.z, this.z, this.z, this.z, R.raw.chp21_1_4__c, this.z, this.z, this.z, R.string.chp21_1_4__c, this.z, this.z, new LocationsAdded(new int[]{-1}), new ShowLocations(false), new IsLocation(false), new ClearLocationsList(false), new RemoveSpecificLocations(new int[]{-1}), new TimeAdded(-1), new ImageLinks(new int[]{-1}), new ImagePositions(new int[]{-1}), new Choice(R.string.btn_continue, 5));
        this.sections[4] = new Section(this.z, this.z, this.z, this.z, R.raw.chp21_1_5__a, this.z, this.z, this.z, R.string.chp21_1_5__a, this.z, this.z, this.z, new LocationsAdded(new int[]{-1}), new ShowLocations(false), new IsLocation(false), new ClearLocationsList(false), new RemoveSpecificLocations(new int[]{-1}), new TimeAdded(-1), new ImageLinks(new int[]{-1}), new ImagePositions(new int[]{-1}), new Choice(R.string.btn_continue, 5));
        this.sections[5] = new Section(R.string.pop21_1_6__b, this.z, this.z, this.z, R.raw.chp21_1_6__a, this.z, this.z, this.z, R.string.chp21_1_6__a, this.z, this.z, this.z, new LocationsAdded(new int[]{-1}), new ShowLocations(false), new IsLocation(false), new ClearLocationsList(false), new RemoveSpecificLocations(new int[]{-1}), new TimeAdded(-1), new ImageLinks(new int[]{-1}), new ImagePositions(new int[]{-1}), new Choice(R.string.btn_succeed, 6), new Choice(R.string.btn_fail, 7));
        this.sections[6] = new Section(R.string.pop21_1_7__b, this.z, this.z, this.z, this.z, R.raw.chp21_1_7__c, this.z, this.z, this.z, R.string.chp21_1_7__c, this.z, this.z, new LocationsAdded(new int[]{-1}), new ShowLocations(false), new IsLocation(false), new ClearLocationsList(false), new RemoveSpecificLocations(new int[]{-1}), new TimeAdded(-1), new ImageLinks(new int[]{-1}), new ImagePositions(new int[]{-1}), new Choice(R.string.btn_continue, 8));
        this.sections[7] = new Section(this.z, this.z, this.z, this.z, R.raw.chp21_1_8__a, this.z, this.z, this.z, R.string.chp21_1_8__a, this.z, this.z, this.z, new LocationsAdded(new int[]{-1}), new ShowLocations(false), new IsLocation(false), new ClearLocationsList(false), new RemoveSpecificLocations(new int[]{-1}), new TimeAdded(-1), new ImageLinks(new int[]{-1}), new ImagePositions(new int[]{-1}), new Choice(R.string.btn_continue, 8));
        this.sections[8] = new Section(R.string.pop21_1_9__b, this.z, this.z, this.z, R.raw.chp21_1_9__a, this.z, this.z, this.z, R.string.chp21_1_9__a, this.z, this.z, this.z, new LocationsAdded(new int[]{-1}), new ShowLocations(false), new IsLocation(false), new ClearLocationsList(false), new RemoveSpecificLocations(new int[]{-1}), new TimeAdded(-1), new ImageLinks(new int[]{-1}), new ImagePositions(new int[]{-1}), new Choice(R.string.btn_succeed, 9), new Choice(R.string.btn_fail, 10));
        this.sections[9] = new Section(R.string.pop21_1_10__b, this.z, this.z, this.z, this.z, R.raw.chp21_1_10__c, this.z, this.z, this.z, R.string.chp21_1_10__c, this.z, this.z, new LocationsAdded(new int[]{-1}), new ShowLocations(false), new IsLocation(false), new ClearLocationsList(false), new RemoveSpecificLocations(new int[]{-1}), new TimeAdded(-1), new ImageLinks(new int[]{-1}), new ImagePositions(new int[]{-1}), new Choice(R.string.btn_continue, 11));
        this.sections[10] = new Section(this.z, this.z, this.z, this.z, R.raw.chp21_1_11__a, this.z, this.z, this.z, R.string.chp21_1_11__a, this.z, this.z, this.z, new LocationsAdded(new int[]{-1}), new ShowLocations(false), new IsLocation(false), new ClearLocationsList(false), new RemoveSpecificLocations(new int[]{-1}), new TimeAdded(-1), new ImageLinks(new int[]{-1}), new ImagePositions(new int[]{-1}), new Choice(R.string.btn_continue, 11));
        this.sections[11] = new Section(this.z, this.z, this.z, this.z, R.raw.chp21_2_1__a, this.z, this.z, this.z, R.string.chp21_2_1__a, this.z, this.z, this.z, new LocationsAdded(new int[]{-1}), new ShowLocations(false), new IsLocation(false), new ClearLocationsList(false), new RemoveSpecificLocations(new int[]{-1}), new TimeAdded(-1), new ImageLinks(new int[]{-1}), new ImagePositions(new int[]{-1}), new Choice(R.string.btn21_2_1__a, 12), new Choice(R.string.btn21_2_1__b, 13));
        this.sections[12] = new Section(R.string.pop21_2_2__b, this.z, this.z, this.z, R.raw.chp21_2_2__a, this.z, this.z, this.z, R.string.chp21_2_2__a, this.z, this.z, this.z, new LocationsAdded(new int[]{-1}), new ShowLocations(false), new IsLocation(false), new ClearLocationsList(false), new RemoveSpecificLocations(new int[]{-1}), new TimeAdded(-1), new ImageLinks(new int[]{-1}), new ImagePositions(new int[]{-1}), new Choice(R.string.btn_succeed, 14), new Choice(R.string.btn_fail, 15));
        this.sections[13] = new Section(this.z, this.z, this.z, this.z, R.raw.chp21_2_3__a, this.z, this.z, this.z, R.string.chp21_2_3__a, this.z, this.z, this.z, new LocationsAdded(new int[]{-1}), new ShowLocations(false), new IsLocation(false), new ClearLocationsList(false), new RemoveSpecificLocations(new int[]{-1}), new TimeAdded(-1), new ImageLinks(new int[]{-1}), new ImagePositions(new int[]{-1}), new Choice(R.string.btn21_2_3__a, 16), new Choice(R.string.btn21_2_3__b, 12));
        this.sections[14] = new Section(R.string.pop21_2_4__b, this.z, this.z, this.z, R.raw.chp21_2_4__a, this.z, this.z, this.z, R.string.chp21_2_4__a, this.z, this.z, this.z, new LocationsAdded(new int[]{-1}), new ShowLocations(false), new IsLocation(false), new ClearLocationsList(false), new RemoveSpecificLocations(new int[]{-1}), new TimeAdded(-1), new ImageLinks(new int[]{-1}), new ImagePositions(new int[]{-1}), new Choice(R.string.btn21_2_4__a, 16), new Choice(R.string.btn21_2_4__b, 13));
        this.sections[15] = new Section(this.z, this.z, this.z, this.z, R.raw.chp21_2_5__a, this.z, this.z, this.z, R.string.chp21_2_5__a, this.z, this.z, this.z, new LocationsAdded(new int[]{-1}), new ShowLocations(false), new IsLocation(false), new ClearLocationsList(false), new RemoveSpecificLocations(new int[]{-1}), new TimeAdded(-1), new ImageLinks(new int[]{-1}), new ImagePositions(new int[]{-1}), new Choice(R.string.btn21_2_5__a, 16), new Choice(R.string.btn21_2_5__b, 13));
        this.sections[16] = new Section(R.string.pop21_2_6__b, this.z, this.z, this.z, R.raw.chp21_2_6__a, this.z, this.z, this.z, R.string.chp21_2_6__a, this.z, this.z, this.z, new LocationsAdded(new int[]{-1}), new ShowLocations(false), new IsLocation(false), new ClearLocationsList(false), new RemoveSpecificLocations(new int[]{-1}), new TimeAdded(-1), new ImageLinks(new int[]{-1}), new ImagePositions(new int[]{-1}), new Choice(R.string.btn_succeed, 17), new Choice(R.string.btn_fail, 18));
        this.sections[17] = new Section(this.z, this.z, this.z, this.z, R.raw.chp21_2_7__a, this.z, this.z, this.z, R.string.chp21_2_7__a, this.z, this.z, this.z, new LocationsAdded(new int[]{-1}), new ShowLocations(false), new IsLocation(false), new ClearLocationsList(false), new RemoveSpecificLocations(new int[]{-1}), new TimeAdded(-1), new ImageLinks(new int[]{-1}), new ImagePositions(new int[]{-1}), new Choice(R.string.btn_continue, 19));
        this.sections[18] = new Section(this.z, this.z, this.z, this.z, R.raw.chp21_2_8__a, this.z, this.z, this.z, R.string.chp21_2_8__a, this.z, this.z, this.z, new LocationsAdded(new int[]{-1}), new ShowLocations(false), new IsLocation(false), new ClearLocationsList(false), new RemoveSpecificLocations(new int[]{-1}), new TimeAdded(-1), new ImageLinks(new int[]{-1}), new ImagePositions(new int[]{-1}), new Choice(R.string.btn_continue, 19));
        this.sections[19] = new Section(this.z, this.z, this.z, this.z, R.raw.chp21_2_9__a, this.z, this.z, this.z, R.string.chp21_2_9__a, this.z, this.z, this.z, new LocationsAdded(new int[]{-1}), new ShowLocations(false), new IsLocation(false), new ClearLocationsList(false), new RemoveSpecificLocations(new int[]{-1}), new TimeAdded(-1), new ImageLinks(new int[]{-1}), new ImagePositions(new int[]{-1}), new Choice(R.string.btn_continue, 28));
        this.sections[20] = new Section(this.z, this.z, this.z, this.z, R.raw.chp21_2_10__a, this.z, this.z, this.z, R.string.chp21_2_10__a, this.z, this.z, this.z, new LocationsAdded(new int[]{-1}), new ShowLocations(false), new IsLocation(false), new ClearLocationsList(false), new RemoveSpecificLocations(new int[]{-1}), new TimeAdded(-1), new ImageLinks(new int[]{-1}), new ImagePositions(new int[]{-1}), new Choice(R.string.btn_continue, 28));
        this.sections[21] = new Section(this.z, this.z, this.z, this.z, R.raw.chp21_2_11__a, this.z, this.z, this.z, R.string.chp21_2_11__a, this.z, this.z, this.z, new LocationsAdded(new int[]{-1}), new ShowLocations(false), new IsLocation(false), new ClearLocationsList(false), new RemoveSpecificLocations(new int[]{-1}), new TimeAdded(-1), new ImageLinks(new int[]{-1}), new ImagePositions(new int[]{-1}), new Choice(R.string.btn_continue, 28));
        this.sections[22] = new Section(this.z, this.z, this.z, this.z, R.raw.chp21_2_12__a, this.z, this.z, this.z, R.string.chp21_2_12__a, this.z, this.z, this.z, new LocationsAdded(new int[]{-1}), new ShowLocations(false), new IsLocation(false), new ClearLocationsList(false), new RemoveSpecificLocations(new int[]{-1}), new TimeAdded(-1), new ImageLinks(new int[]{-1}), new ImagePositions(new int[]{-1}), new Choice(R.string.btn_continue, 28));
        this.sections[23] = new Section(R.string.pop21_2_13__b, this.z, this.z, this.z, R.raw.chp21_2_13__a, this.z, this.z, this.z, R.string.chp21_2_13__a, this.z, this.z, this.z, new LocationsAdded(new int[]{-1}), new ShowLocations(false), new IsLocation(false), new ClearLocationsList(false), new RemoveSpecificLocations(new int[]{-1}), new TimeAdded(-1), new ImageLinks(new int[]{-1}), new ImagePositions(new int[]{-1}), new Choice(R.string.btn_continue, 28));
        this.sections[24] = new Section(this.z, this.z, this.z, this.z, R.raw.chp21_2_14__a, this.z, this.z, this.z, R.string.chp21_2_14__a, this.z, this.z, this.z, new LocationsAdded(new int[]{-1}), new ShowLocations(false), new IsLocation(false), new ClearLocationsList(false), new RemoveSpecificLocations(new int[]{-1}), new TimeAdded(-1), new ImageLinks(new int[]{-1}), new ImagePositions(new int[]{-1}), new Choice(R.string.btn_continue, 28));
        this.sections[25] = new Section(R.string.pop21_2_15__b, this.z, this.z, this.z, R.raw.chp21_2_15__a, this.z, this.z, this.z, R.string.chp21_2_15__a, this.z, this.z, this.z, new LocationsAdded(new int[]{-1}), new ShowLocations(false), new IsLocation(false), new ClearLocationsList(false), new RemoveSpecificLocations(new int[]{-1}), new TimeAdded(-1), new ImageLinks(new int[]{-1}), new ImagePositions(new int[]{-1}), new Choice(R.string.btn_continue, 28));
        this.sections[26] = new Section(this.z, this.z, this.z, this.z, R.raw.chp21_2_16__a, this.z, this.z, this.z, R.string.chp21_2_16__a, this.z, this.z, this.z, new LocationsAdded(new int[]{-1}), new ShowLocations(false), new IsLocation(false), new ClearLocationsList(false), new RemoveSpecificLocations(new int[]{-1}), new TimeAdded(-1), new ImageLinks(new int[]{-1}), new ImagePositions(new int[]{-1}), new Choice(R.string.btn_continue, 28));
        this.sections[27] = new Section(this.z, this.z, this.z, this.z, R.raw.chp21_2_17__a, this.z, this.z, this.z, R.string.chp21_2_17__a, this.z, this.z, this.z, new LocationsAdded(new int[]{-1}), new ShowLocations(false), new IsLocation(false), new ClearLocationsList(false), new RemoveSpecificLocations(new int[]{-1}), new TimeAdded(-1), new ImageLinks(new int[]{-1}), new ImagePositions(new int[]{-1}), new Choice(R.string.btn_continue, 28));
        this.sections[28] = new Section(R.string.pop21_2_18__b, this.z, this.z, this.z, this.z, this.z, this.z, this.z, this.z, this.z, this.z, this.z, new LocationsAdded(new int[]{-1}), new ShowLocations(false), new IsLocation(false), new ClearLocationsList(false), new RemoveSpecificLocations(new int[]{-1}), new TimeAdded(-1), new ImageLinks(new int[]{-1}), new ImagePositions(new int[]{-1}), new Choice(R.string.btn21_2_18__a, 26), new Choice(R.string.btn21_2_18__b, 27), new Choice(R.string.btn21_2_18__c, 20), new Choice(R.string.btn21_2_18__d, 21), new Choice(R.string.btn21_2_18__e, 22), new Choice(R.string.btn21_2_18__f, 23), new Choice(R.string.btn21_2_18__g, 24), new Choice(R.string.btn21_2_18__h, 25), new Choice(R.string.btn21_2_18__i, 29));
        this.sections[29] = new Section(this.z, this.z, this.z, this.z, R.raw.chp21_2_19__a, this.z, this.z, this.z, R.string.chp21_2_19__a, this.z, this.z, this.z, new LocationsAdded(new int[]{-1}), new ShowLocations(false), new IsLocation(false), new ClearLocationsList(false), new RemoveSpecificLocations(new int[]{-1}), new TimeAdded(-1), new ImageLinks(new int[]{-1}), new ImagePositions(new int[]{-1}), new Choice(R.string.btn21_2_19__a, 30), new Choice(R.string.btn21_2_19__b, 31));
        this.sections[30] = new Section(R.string.pop21_2_20__b, R.string.pop21_2_20__d, this.z, this.z, this.z, R.raw.chp21_2_20__c, this.z, this.z, this.z, R.string.chp21_2_20__c, this.z, this.z, new LocationsAdded(new int[]{-1}), new ShowLocations(false), new IsLocation(false), new ClearLocationsList(false), new RemoveSpecificLocations(new int[]{-1}), new TimeAdded(-1), new ImageLinks(new int[]{-1}), new ImagePositions(new int[]{-1}), new Choice(R.string.btn_encounter, 32));
        this.sections[31] = new Section(R.string.pop21_2_21__b, R.string.pop21_2_21__d, this.z, this.z, this.z, R.raw.chp21_2_21__c, this.z, this.z, this.z, R.string.chp21_2_21__c, this.z, this.z, new LocationsAdded(new int[]{-1}), new ShowLocations(false), new IsLocation(false), new ClearLocationsList(false), new RemoveSpecificLocations(new int[]{-1}), new TimeAdded(-1), new ImageLinks(new int[]{-1}), new ImagePositions(new int[]{-1}), new Choice(R.string.btn_encounter, 32));
        this.sections[32] = new Section(R.string.encounter_to_epilogue, this.z, this.z, this.z, R.raw.encounter_audio, this.z, this.z, this.z, this.z, this.z, this.z, this.z, new LocationsAdded(new int[]{-1}), new ShowLocations(false), new IsLocation(false), new ClearLocationsList(false), new RemoveSpecificLocations(new int[]{-1}), new TimeAdded(-1), new ImageLinks(new int[]{R.drawable.chapter_21}), new ImagePositions(new int[]{1}), new Choice(R.string.btn_epilogue, 33));
        this.sections[33] = new Section(this.z, this.z, this.z, this.z, this.z, this.z, this.z, this.z, this.z, this.z, this.z, this.z, new LocationsAdded(new int[]{-1}), new ShowLocations(false), new IsLocation(false), new ClearLocationsList(false), new RemoveSpecificLocations(new int[]{-1}), new TimeAdded(-1), new ImageLinks(new int[]{-1}), new ImagePositions(new int[]{-1}), new Choice(R.string.btn21_epi_1__a, 34), new Choice(R.string.btn21_epi_1__b, 35));
        this.sections[34] = new Section(this.z, this.z, this.z, this.z, R.raw.chp21_epi_2__a, this.z, this.z, this.z, R.string.chp21_epi_2__a, this.z, this.z, this.z, new LocationsAdded(new int[]{-1}), new ShowLocations(false), new IsLocation(false), new ClearLocationsList(false), new RemoveSpecificLocations(new int[]{-1}), new TimeAdded(-1), new ImageLinks(new int[]{-1}), new ImagePositions(new int[]{-1}), new Choice(R.string.btn_continue, 36));
        this.sections[35] = new Section(this.z, this.z, this.z, this.z, R.raw.chp21_epi_3__a, this.z, this.z, this.z, R.string.chp21_epi_3__a, this.z, this.z, this.z, new LocationsAdded(new int[]{-1}), new ShowLocations(false), new IsLocation(false), new ClearLocationsList(false), new RemoveSpecificLocations(new int[]{-1}), new TimeAdded(-1), new ImageLinks(new int[]{-1}), new ImagePositions(new int[]{-1}), new Choice(R.string.btn_continue, 38));
        this.sections[36] = new Section(this.z, this.z, this.z, this.z, R.raw.chp21_epi_4__a, this.z, this.z, this.z, R.string.chp21_epi_4__a, this.z, this.z, this.z, new LocationsAdded(new int[]{-1}), new ShowLocations(false), new IsLocation(false), new ClearLocationsList(false), new RemoveSpecificLocations(new int[]{-1}), new TimeAdded(-1), new ImageLinks(new int[]{-1}), new ImagePositions(new int[]{-1}), new Choice(R.string.btn_continue, 37));
        this.sections[37] = new Section(R.string.pop21_epi_5__b, this.z, this.z, this.z, R.raw.chp21_epi_5__a, this.z, this.z, this.z, R.string.chp21_epi_5__a, this.z, this.z, this.z, new LocationsAdded(new int[]{-1}), new ShowLocations(false), new IsLocation(false), new ClearLocationsList(false), new RemoveSpecificLocations(new int[]{-1}), new TimeAdded(-1), new ImageLinks(new int[]{-1}), new ImagePositions(new int[]{-1}), new Choice(R.string.btn21_epi_5__a, -1));
        this.sections[38] = new Section(R.string.pop21_epi_6__b, this.z, this.z, this.z, R.raw.chp21_epi_6__a, this.z, this.z, this.z, R.string.chp21_epi_6__a, this.z, this.z, this.z, new LocationsAdded(new int[]{-1}), new ShowLocations(false), new IsLocation(false), new ClearLocationsList(false), new RemoveSpecificLocations(new int[]{-1}), new TimeAdded(-1), new ImageLinks(new int[]{-1}), new ImagePositions(new int[]{-1}), new Choice(R.string.btn21_epi_6__a, -1));
    }
}
